version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name test0deploy --s3-location s3://rastwork.s3/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src
